### ISSUE TITLE
数据库的sql没有

### ISSUE THREAD

**Issue by amoxuk** [haibofaith/MaveDemo#1]
没有数据库文档 应该包括创建和插入的测试数据

**Comment by haibofaith** [comment]
已上传

**Comment by amoxuk** [comment]
thx------------------ 原始邮件 ------------------发件人: haibofaith  <notifications@github.com>发送时间: 2017年12月4日 19:12收件人: haibofaith/MaveDemo <MaveDemo@noreply.github.com>抄送: amoxu <amo.gkx@gmail.com>, Author <author@noreply.github.com>主题: 回复：[haibofaith/MaveDemo] 数据库的sql没有 (#1)已上传

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/haibofaith/MaveDemo","title":"haibofaith/MaveDemo","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/haibofaith/MaveDemo"}},"updates":{"snippets":[{"icon":"PERSON","message":"@haibofaith in #1: 已上传"}],"action":{"name":"View Issue","url":"https://github.com/haibofaith/MaveDemo/issues/1#issuecomment-348931907"}}}
